version: '3.7'

services:
  geth-bootnode:
    container_name: geth-bootnode
    hostname: geth-bootnode
    env_file:
      - .env
    image: private-node
    # build:
    #   context: .
    #   args:
    #     - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command:
      --nodekeyhex=${PRIVATE_NODE_KEY}
      --nodiscover
      --allow-insecure-unlock
      --ipcdisable
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
      --mine
      --miner.etherbase=${REWARD_ADDRESS}
    volumes:
      - geth_bootnode:/root/.ethereum/
    networks:
      priv-eth-net:

  geth-rpc-endpoint:
    container_name: geth-rpc-endpoint
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: private-node
    depends_on:
      - geth-bootnode    
    command:
      --bootnodes="enode://${PUBLIC_NODE_KEY}@geth-bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal,miner"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
      --syncmode="full"
    volumes:
      - geth_rpc_endpoint:/root/.ethereum/
    ports:
      - "8545:8545"
      - "8546:8546"
    networks:
      priv-eth-net:

  geth-miner:
    container_name: geth-miner
    hostname: geth-miner
    env_file:
      - .env
    image: private-node
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://${PUBLIC_NODE_KEY}@geth-bootnode:30303"
      --allow-insecure-unlock
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
      --syncmode="full"
      --miner.etherbase=${REWARD_ADDRESS}
    volumes:
      - geth_miner:/root/.ethereum/
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28

volumes:
  geth_bootnode:
    driver: local
  geth_rpc_endpoint:
    driver: local
  geth_miner:
    driver: local
